const trackDir = "";
const bpm = 124;
const parts = [
{ file: "1.wav", length: 8, loop: 0 },
{ file: "2.wav", length: 8, loop: 0 },
{ file: "3.wav", length: 8, loop: 0 },
{ file: "4.wav", length: 8, loop: 0 },
{ file: "5.wav", length: 8, loop: 0 }, 
{ file: "6.wav", length: 8, loop: 0 },
{ file: "7.wav", length: 8, loop: 0 },
{ file: "8.wav", length: 8, loop: 0 },
{ file: "10.wav", length: 8, loop: 0 },
{ file: "11.wav", length: 8, loop: 0 },
{ file: "12.wav", length: 8, loop: 0 },
{ file: "13.wav", length: 8, loop: 0 },
{ file: "14.wav", length: 8, loop: 0 },
{ file: "15.wav", length: 8, loop: 1 },
{ file: "16.wav", length: 1, loop: 0 },
{ file: "18.wav", length: 2, loop: 0 },
{ file: "17D.wav", length: 2, loop: 0 },
{ file: "break_ext1.wav", length: 8, loop: 1 },
{ file: "break_ext2.wav", length: 8, loop: 1 },
{ file: "break_ext3.wav", length: 8, loop: 1 },
{ file: "break_ext4.wav", length: 8, loop: 1 },
{ file: "break_ext5.wav", length: 8, loop: 1 },
{ file: "break_ext6.wav", length: 8, loop: 1 },
{ file: "break_ext7.wav", length: 8, loop: 1 },
{ file: "break_ext8.wav", length: 8, loop: 1 },
{ file: "break_ext9.wav", length: 8, loop: 1 },
{ file: "break_ext10.wav", length: 8, loop: 1 },
{ file: "break_ext11.wav", length: 8, loop: 1 },
{ file: "break_ext12.wav", length: 8, loop: 1 },
{ file: "break_ext13.wav", length: 8, loop: 1 },
{ file: "break_ext14.wav", length: 8, loop: 1 },
];

const presets = [];
presets.push([   
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1, 
    1,
    1,
    1,
    1, 
    1,
    1,
    1,
    4, 
    4,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1, 
    1,
    1,
    1,
]);
presets.push([
    0,
    0,
    0,
    1,
    1,
    0,
    0,
    0, 
    1,
    0,
    1,
    1, 
    1,
    1,
    0,
    0, 
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1, 
    1,
    1,
    1,
]);
presets.push([ 
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0, 
    0,
    0,
    0,
    0, 
    0,
    0,
    1,
    4, 
    4,
    1,
    1,
    0,
    1,
    1,
    1,
    1,
    0,
    0,
    0,
    1, 
    0,
    0,
    0,
]);
presets.push([
    0,0,0,0,0,
    0,0,0,0,0,
    0,0,0,0,0,
    0,0,0,0,0,
    0,0,0,0,0,
    0,0,0,0,0,
    0,0,0,0,0
]);

const downloadName = "Oluwa.wav"
const boxHeight = 50; //min height == 40 -> otherwise clickable buttons are to small
const reverseScrolling = false;
